### ISSUE TITLE
M3: Spike: Investigate how to test cmcd-analyzer with no local player

### ISSUE THREAD

**Issue by CamiloBorba09** [montevideo-tech/cmcd-analyzer#24]
The goal of this ticket is to identify how to use the cmcd-analyzer with a browser that is not hosted locally. To do this, you can run the cmcd-analyzer using `docker-compose` up and test it with the following players:
- https://players.akamai.com/players/dashjs
- https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html
- https://livepush.io/hls-player/index.html

AC
1. Document whether it works and if not, investigate what is causing the issue and possible solutions to those problems.

**Comment by adriansqualabs** [comment]
Some players works fine if you host the analyzer on a public server but there are problems when you try to run the analyzer locally and a web public hosted player on your computer. 
The workaround could be:

-  Some local server with another network configuration that not relay on the localhost.
-  Use HTTPS

In the other hand our cmcd demo app hosted on github pages works fine with the analyzer running locally, we should validate if this behavior is enough to our design.
