### ISSUE TITLE
M3: Crate video-test controller

### ISSUE THREAD

**Issue by CamiloBorba09** [montevideo-tech/cmcd-analyzer#7]
We need to create the proxy's video-test controller. This controller should receive a request and return the CDN response.

AC
1. Create main controller
2. Test this with a player with default URL harcoded in the code.

**Comment by JoaquinBCh** [comment]
This ticket is blocked by 

- [M3: Define CMCD request type](https://github.com/montevideo-tech/cmcd-analyzer/issues/4)
- [M3: Obtain and validate cmcd params](https://github.com/montevideo-tech/cmcd-analyzer/issues/5)
